"""Deterministic generator for Q-GREEN FLEET sample pack and fuel catalog.

Generates:
  - data/fuel_catalog/fuels.json (IMO MEPC.391(81) WtW LCA pathways)
  - data/sample/vessels.json (12 diverse commercial vessels: Container, Bulk, Tanker)
  - data/sample/ports.json (10 major global maritime hubs with OPS & bunker stocks)
  - data/sample/routes.json (4 strategic corridors with segmented legs, ECA, and depths)
  - data/scenarios/scenarios.json (6 uncertainty scenarios: storm, congestion, shocks, outage)
"""

import json
import os
from typing import Any, Dict, List


def get_fuels() -> List[Dict[str, Any]]:
    return [
        {
            "pathway_id": "hfo",
            "name": "Heavy Fuel Oil (0.5% VLSFO Baseline)",
            "category": "fossil",
            "energy_density_mj_kg": 40.2,
            "price_per_tonne_usd": 580.0,
            "wtt_gco2e_mj": 13.5,
            "ttw_co2_g_mj": 77.4,
            "ttw_ch4_slip_g_mj": 0.0,
            "ttw_n2o_g_mj": 0.004,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 92.0,
            "tank_volume_penalty": 1.0,
            "bunker_availability_score": 0.98,
            "compat_engine_types": ["Standard 2-Stroke", "Standard 4-Stroke"],
            "source_ref": "IMO MEPC.391(81) Table 2 (Baseline)",
            "provenance": "reported",
        },
        {
            "pathway_id": "mgo",
            "name": "Marine Gas Oil (0.10% S Distillate)",
            "category": "fossil",
            "energy_density_mj_kg": 42.7,
            "price_per_tonne_usd": 820.0,
            "wtt_gco2e_mj": 14.4,
            "ttw_co2_g_mj": 74.5,
            "ttw_ch4_slip_g_mj": 0.0,
            "ttw_n2o_g_mj": 0.004,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 90.0,
            "tank_volume_penalty": 0.98,
            "bunker_availability_score": 0.99,
            "compat_engine_types": ["Standard 2-Stroke", "Standard 4-Stroke", "Dual-Fuel LNG", "Dual-Fuel Methanol"],
            "source_ref": "IMO MEPC.391(81) Table 2 (ECA Compliant)",
            "provenance": "reported",
        },
        {
            "pathway_id": "lng_fossil",
            "name": "Liquefied Natural Gas (Fossil Otto Cycle)",
            "category": "fossil",
            "energy_density_mj_kg": 49.1,
            "price_per_tonne_usd": 750.0,
            "wtt_gco2e_mj": 18.5,
            "ttw_co2_g_mj": 56.1,
            "ttw_ch4_slip_g_mj": 0.55,
            "ttw_n2o_g_mj": 0.001,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 90.3,
            "tank_volume_penalty": 1.4,
            "bunker_availability_score": 0.65,
            "compat_engine_types": ["Dual-Fuel LNG"],
            "source_ref": "IMO MEPC.391(81) Table 3",
            "provenance": "reported",
        },
        {
            "pathway_id": "lng_bio",
            "name": "Liquefied Biomethane (Bio-LNG from Organic Residues)",
            "category": "bio",
            "energy_density_mj_kg": 49.1,
            "price_per_tonne_usd": 1380.0,
            "wtt_gco2e_mj": 12.0,
            "ttw_co2_g_mj": 0.0,
            "ttw_ch4_slip_g_mj": 0.50,
            "ttw_n2o_g_mj": 0.001,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 26.3,
            "tank_volume_penalty": 1.4,
            "bunker_availability_score": 0.35,
            "compat_engine_types": ["Dual-Fuel LNG"],
            "source_ref": "IMO MEPC.391(81) Table 3",
            "provenance": "reported",
        },
        {
            "pathway_id": "methanol_grey",
            "name": "Grey Methanol (Natural Gas Steam Reforming)",
            "category": "fossil",
            "energy_density_mj_kg": 19.9,
            "price_per_tonne_usd": 430.0,
            "wtt_gco2e_mj": 31.0,
            "ttw_co2_g_mj": 68.9,
            "ttw_ch4_slip_g_mj": 0.0,
            "ttw_n2o_g_mj": 0.0,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 99.9,
            "tank_volume_penalty": 2.1,
            "bunker_availability_score": 0.45,
            "compat_engine_types": ["Dual-Fuel Methanol"],
            "source_ref": "IMO MEPC.391(81) Table 4 (High Upstream Footprint)",
            "provenance": "reported",
        },
        {
            "pathway_id": "methanol_bio",
            "name": "Bio-Methanol (Forestry & Black Liquor Residues)",
            "category": "bio",
            "energy_density_mj_kg": 19.9,
            "price_per_tonne_usd": 890.0,
            "wtt_gco2e_mj": 18.0,
            "ttw_co2_g_mj": 0.0,
            "ttw_ch4_slip_g_mj": 0.0,
            "ttw_n2o_g_mj": 0.0,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 18.0,
            "tank_volume_penalty": 2.1,
            "bunker_availability_score": 0.30,
            "compat_engine_types": ["Dual-Fuel Methanol"],
            "source_ref": "IMO MEPC.391(81) Table 4",
            "provenance": "reported",
        },
        {
            "pathway_id": "methanol_e",
            "name": "E-Methanol (Green Hydrogen + Direct Air Capture CO2)",
            "category": "e-fuel",
            "energy_density_mj_kg": 19.9,
            "price_per_tonne_usd": 1260.0,
            "wtt_gco2e_mj": 8.5,
            "ttw_co2_g_mj": 0.0,
            "ttw_ch4_slip_g_mj": 0.0,
            "ttw_n2o_g_mj": 0.0,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 8.5,
            "tank_volume_penalty": 2.1,
            "bunker_availability_score": 0.18,
            "compat_engine_types": ["Dual-Fuel Methanol"],
            "source_ref": "IMO MEPC.391(81) Table 4",
            "provenance": "reported",
        },
        {
            "pathway_id": "ammonia_grey",
            "name": "Grey Ammonia (Haber-Bosch from Fossil Gas)",
            "category": "fossil",
            "energy_density_mj_kg": 18.6,
            "price_per_tonne_usd": 560.0,
            "wtt_gco2e_mj": 122.0,
            "ttw_co2_g_mj": 0.0,
            "ttw_ch4_slip_g_mj": 0.0,
            "ttw_n2o_g_mj": 0.015,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 126.0,
            "tank_volume_penalty": 2.4,
            "bunker_availability_score": 0.25,
            "compat_engine_types": ["Ammonia Dual-Fuel"],
            "source_ref": "IMO MEPC.391(81) Table 5 (High Upstream Emissions)",
            "provenance": "reported",
        },
        {
            "pathway_id": "ammonia_green",
            "name": "Green Ammonia (Electrolytic Green H2 + N2)",
            "category": "e-fuel",
            "energy_density_mj_kg": 18.6,
            "price_per_tonne_usd": 1150.0,
            "wtt_gco2e_mj": 9.2,
            "ttw_co2_g_mj": 0.0,
            "ttw_ch4_slip_g_mj": 0.0,
            "ttw_n2o_g_mj": 0.012,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 12.4,
            "tank_volume_penalty": 2.4,
            "bunker_availability_score": 0.12,
            "compat_engine_types": ["Ammonia Dual-Fuel"],
            "source_ref": "IMO MEPC.391(81) Table 5",
            "provenance": "reported",
        },
        {
            "pathway_id": "h2_green",
            "name": "Liquefied Green Hydrogen (Renewable Electrolysis LH2)",
            "category": "zero_carbon",
            "energy_density_mj_kg": 120.0,
            "price_per_tonne_usd": 4200.0,
            "wtt_gco2e_mj": 14.0,
            "ttw_co2_g_mj": 0.0,
            "ttw_ch4_slip_g_mj": 0.0,
            "ttw_n2o_g_mj": 0.0,
            "gwp_ch4": 28.0,
            "gwp_n2o": 265.0,
            "wtw_gco2e_mj": 14.0,
            "tank_volume_penalty": 4.3,
            "bunker_availability_score": 0.05,
            "compat_engine_types": ["Hydrogen Fuel Cell"],
            "source_ref": "IMO MEPC.391(81) Guidelines",
            "provenance": "estimated",
        },
    ]


def get_vessels() -> List[Dict[str, Any]]:
    return [
        # Containers
        {
            "vessel_id": "IMO9811001",
            "name": "Atlantic Pioneer",
            "vessel_type": "Container",
            "dwt": 195000.0,
            "capacity_teu": 20000,
            "design_speed_knots": 19.5,
            "min_speed_knots": 11.0,
            "max_speed_knots": 22.5,
            "draft_design_m": 16.0,
            "engine_kw": 58000.0,
            "sfoc_base_g_kwh": 168.0,
            "speed_exponent_n": 3.15,
            "admiralty_coefficient": 580.0,
            "fuel_compat": ["hfo", "mgo", "methanol_grey", "methanol_bio", "methanol_e"],
            "tank_capacities_tonnes": {"hfo": 5000.0, "mgo": 1200.0, "methanol_grey": 6500.0, "methanol_bio": 6500.0, "methanol_e": 6500.0},
            "ops_compatible": True,
            "ops_power_kw": 2200.0,
            "hull_factor": 1.02,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9811002",
            "name": "Pacific Voyager",
            "vessel_type": "Container",
            "dwt": 145000.0,
            "capacity_teu": 14000,
            "design_speed_knots": 18.5,
            "min_speed_knots": 10.5,
            "max_speed_knots": 21.5,
            "draft_design_m": 15.2,
            "engine_kw": 46000.0,
            "sfoc_base_g_kwh": 170.0,
            "speed_exponent_n": 3.10,
            "admiralty_coefficient": 550.0,
            "fuel_compat": ["hfo", "mgo", "lng_fossil", "lng_bio"],
            "tank_capacities_tonnes": {"hfo": 3800.0, "mgo": 800.0, "lng_fossil": 4200.0, "lng_bio": 4200.0},
            "ops_compatible": True,
            "ops_power_kw": 1800.0,
            "hull_factor": 1.00,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9811003",
            "name": "Nordic Express",
            "vessel_type": "Container",
            "dwt": 68000.0,
            "capacity_teu": 5200,
            "design_speed_knots": 17.5,
            "min_speed_knots": 10.0,
            "max_speed_knots": 20.0,
            "draft_design_m": 12.8,
            "engine_kw": 28000.0,
            "sfoc_base_g_kwh": 175.0,
            "speed_exponent_n": 3.05,
            "admiralty_coefficient": 490.0,
            "fuel_compat": ["hfo", "mgo"],
            "tank_capacities_tonnes": {"hfo": 2400.0, "mgo": 600.0},
            "ops_compatible": False,
            "ops_power_kw": 1200.0,
            "hull_factor": 1.08,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9811004",
            "name": "Baltic Feeder",
            "vessel_type": "Container",
            "dwt": 24000.0,
            "capacity_teu": 1800,
            "design_speed_knots": 15.5,
            "min_speed_knots": 9.0,
            "max_speed_knots": 18.0,
            "draft_design_m": 9.2,
            "engine_kw": 12500.0,
            "sfoc_base_g_kwh": 182.0,
            "speed_exponent_n": 2.95,
            "admiralty_coefficient": 440.0,
            "fuel_compat": ["mgo", "methanol_bio", "methanol_e"],
            "tank_capacities_tonnes": {"mgo": 550.0, "methanol_bio": 1100.0, "methanol_e": 1100.0},
            "ops_compatible": True,
            "ops_power_kw": 750.0,
            "hull_factor": 1.01,
            "provenance": "reported",
        },
        # Bulk Carriers
        {
            "vessel_id": "IMO9722001",
            "name": "Capesize Titan",
            "vessel_type": "Bulk Carrier",
            "dwt": 182000.0,
            "capacity_teu": None,
            "design_speed_knots": 14.0,
            "min_speed_knots": 9.0,
            "max_speed_knots": 16.0,
            "draft_design_m": 18.2,
            "engine_kw": 18500.0,
            "sfoc_base_g_kwh": 165.0,
            "speed_exponent_n": 2.85,
            "admiralty_coefficient": 610.0,
            "fuel_compat": ["hfo", "mgo", "lng_fossil", "lng_bio"],
            "tank_capacities_tonnes": {"hfo": 4200.0, "mgo": 600.0, "lng_fossil": 3600.0, "lng_bio": 3600.0},
            "ops_compatible": False,
            "ops_power_kw": 600.0,
            "hull_factor": 1.04,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9722002",
            "name": "Panamax Mineral",
            "vessel_type": "Bulk Carrier",
            "dwt": 76000.0,
            "capacity_teu": None,
            "design_speed_knots": 13.5,
            "min_speed_knots": 8.5,
            "max_speed_knots": 15.2,
            "draft_design_m": 14.1,
            "engine_kw": 9800.0,
            "sfoc_base_g_kwh": 172.0,
            "speed_exponent_n": 2.80,
            "admiralty_coefficient": 570.0,
            "fuel_compat": ["hfo", "mgo", "ammonia_grey", "ammonia_green"],
            "tank_capacities_tonnes": {"hfo": 2100.0, "mgo": 400.0, "ammonia_grey": 3800.0, "ammonia_green": 3800.0},
            "ops_compatible": True,
            "ops_power_kw": 500.0,
            "hull_factor": 1.03,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9722003",
            "name": "Supramax Grain",
            "vessel_type": "Bulk Carrier",
            "dwt": 56000.0,
            "capacity_teu": None,
            "design_speed_knots": 13.0,
            "min_speed_knots": 8.0,
            "max_speed_knots": 14.5,
            "draft_design_m": 12.5,
            "engine_kw": 8200.0,
            "sfoc_base_g_kwh": 175.0,
            "speed_exponent_n": 2.82,
            "admiralty_coefficient": 530.0,
            "fuel_compat": ["hfo", "mgo"],
            "tank_capacities_tonnes": {"hfo": 1800.0, "mgo": 350.0},
            "ops_compatible": False,
            "ops_power_kw": 450.0,
            "hull_factor": 1.10,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9722004",
            "name": "Handy Timber",
            "vessel_type": "Bulk Carrier",
            "dwt": 34000.0,
            "capacity_teu": None,
            "design_speed_knots": 12.5,
            "min_speed_knots": 7.5,
            "max_speed_knots": 14.0,
            "draft_design_m": 10.1,
            "engine_kw": 6400.0,
            "sfoc_base_g_kwh": 178.0,
            "speed_exponent_n": 2.85,
            "admiralty_coefficient": 490.0,
            "fuel_compat": ["mgo", "methanol_bio", "methanol_e"],
            "tank_capacities_tonnes": {"mgo": 450.0, "methanol_bio": 950.0, "methanol_e": 950.0},
            "ops_compatible": True,
            "ops_power_kw": 400.0,
            "hull_factor": 1.01,
            "provenance": "reported",
        },
        # Tankers
        {
            "vessel_id": "IMO9633001",
            "name": "VLCC Oceanic",
            "vessel_type": "Tanker",
            "dwt": 310000.0,
            "capacity_teu": None,
            "design_speed_knots": 15.0,
            "min_speed_knots": 9.5,
            "max_speed_knots": 16.5,
            "draft_design_m": 22.0,
            "engine_kw": 27500.0,
            "sfoc_base_g_kwh": 164.0,
            "speed_exponent_n": 2.90,
            "admiralty_coefficient": 630.0,
            "fuel_compat": ["hfo", "mgo", "lng_fossil", "lng_bio"],
            "tank_capacities_tonnes": {"hfo": 5500.0, "mgo": 800.0, "lng_fossil": 5000.0, "lng_bio": 5000.0},
            "ops_compatible": False,
            "ops_power_kw": 950.0,
            "hull_factor": 1.02,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9633002",
            "name": "Suezmax Energy",
            "vessel_type": "Tanker",
            "dwt": 158000.0,
            "capacity_teu": None,
            "design_speed_knots": 14.5,
            "min_speed_knots": 9.0,
            "max_speed_knots": 16.0,
            "draft_design_m": 16.8,
            "engine_kw": 16800.0,
            "sfoc_base_g_kwh": 168.0,
            "speed_exponent_n": 2.88,
            "admiralty_coefficient": 590.0,
            "fuel_compat": ["hfo", "mgo", "ammonia_grey", "ammonia_green"],
            "tank_capacities_tonnes": {"hfo": 3200.0, "mgo": 500.0, "ammonia_grey": 5500.0, "ammonia_green": 5500.0},
            "ops_compatible": True,
            "ops_power_kw": 800.0,
            "hull_factor": 1.05,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9633003",
            "name": "Aframax Gulf",
            "vessel_type": "Tanker",
            "dwt": 105000.0,
            "capacity_teu": None,
            "design_speed_knots": 14.0,
            "min_speed_knots": 8.5,
            "max_speed_knots": 15.5,
            "draft_design_m": 14.5,
            "engine_kw": 13200.0,
            "sfoc_base_g_kwh": 172.0,
            "speed_exponent_n": 2.86,
            "admiralty_coefficient": 550.0,
            "fuel_compat": ["hfo", "mgo"],
            "tank_capacities_tonnes": {"hfo": 2600.0, "mgo": 450.0},
            "ops_compatible": False,
            "ops_power_kw": 700.0,
            "hull_factor": 1.07,
            "provenance": "reported",
        },
        {
            "vessel_id": "IMO9633004",
            "name": "Clean Chemical",
            "vessel_type": "Tanker",
            "dwt": 49000.0,
            "capacity_teu": None,
            "design_speed_knots": 13.8,
            "min_speed_knots": 8.0,
            "max_speed_knots": 15.0,
            "draft_design_m": 11.5,
            "engine_kw": 7800.0,
            "sfoc_base_g_kwh": 176.0,
            "speed_exponent_n": 2.84,
            "admiralty_coefficient": 500.0,
            "fuel_compat": ["mgo", "methanol_grey", "methanol_bio", "methanol_e"],
            "tank_capacities_tonnes": {"mgo": 450.0, "methanol_grey": 1200.0, "methanol_bio": 1200.0, "methanol_e": 1200.0},
            "ops_compatible": True,
            "ops_power_kw": 600.0,
            "hull_factor": 1.00,
            "provenance": "reported",
        },
    ]


def get_ports() -> List[Dict[str, Any]]:
    return [
        {
            "port_id": "NLRTM",
            "name": "Port of Rotterdam",
            "unlocode": "NLRTM",
            "lat": 51.95,
            "lon": 4.13,
            "max_draft_m": 24.0,
            "ops_available": True,
            "ops_price_per_kwh": 0.22,
            "ops_clean_grid_factor": 180.0,
            "bunker_stock_tonnes": {
                "hfo": 50000.0,
                "mgo": 25000.0,
                "lng_fossil": 18000.0,
                "lng_bio": 6000.0,
                "methanol_grey": 12000.0,
                "methanol_bio": 5000.0,
                "methanol_e": 2500.0,
                "ammonia_green": 1500.0,
            },
            "bunker_price_spread": {"hfo": 1.0, "mgo": 1.0, "lng_fossil": 0.98, "methanol_bio": 1.02},
            "congestion_delay_mean_h": 4.5,
            "congestion_delay_std_h": 2.0,
            "provenance": "reported",
        },
        {
            "port_id": "SGSIN",
            "name": "Port of Singapore",
            "unlocode": "SGSIN",
            "lat": 1.28,
            "lon": 103.85,
            "max_draft_m": 20.0,
            "ops_available": True,
            "ops_price_per_kwh": 0.24,
            "ops_clean_grid_factor": 340.0,
            "bunker_stock_tonnes": {
                "hfo": 80000.0,
                "mgo": 40000.0,
                "lng_fossil": 22000.0,
                "lng_bio": 4000.0,
                "methanol_grey": 16000.0,
                "methanol_bio": 4500.0,
                "methanol_e": 2000.0,
                "ammonia_green": 1000.0,
            },
            "bunker_price_spread": {"hfo": 0.97, "mgo": 0.98, "lng_fossil": 0.96},
            "congestion_delay_mean_h": 5.0,
            "congestion_delay_std_h": 2.5,
            "provenance": "reported",
        },
        {
            "port_id": "CNSHA",
            "name": "Port of Shanghai (Yangshan)",
            "unlocode": "CNSHA",
            "lat": 30.62,
            "lon": 122.06,
            "max_draft_m": 16.5,
            "ops_available": True,
            "ops_price_per_kwh": 0.19,
            "ops_clean_grid_factor": 520.0,
            "bunker_stock_tonnes": {
                "hfo": 60000.0,
                "mgo": 30000.0,
                "lng_fossil": 15000.0,
                "methanol_grey": 10000.0,
                "methanol_bio": 3000.0,
            },
            "bunker_price_spread": {"hfo": 0.99, "mgo": 0.99},
            "congestion_delay_mean_h": 6.5,
            "congestion_delay_std_h": 3.0,
            "provenance": "reported",
        },
        {
            "port_id": "USLAX",
            "name": "Port of Los Angeles",
            "unlocode": "USLAX",
            "lat": 33.74,
            "lon": -118.26,
            "max_draft_m": 16.2,
            "ops_available": True,
            "ops_price_per_kwh": 0.28,
            "ops_clean_grid_factor": 210.0,
            "bunker_stock_tonnes": {
                "mgo": 20000.0,
                "lng_fossil": 12000.0,
                "lng_bio": 4500.0,
                "methanol_bio": 3500.0,
                "methanol_e": 1800.0,
            },
            "bunker_price_spread": {"mgo": 1.05, "lng_bio": 1.02},
            "congestion_delay_mean_h": 7.0,
            "congestion_delay_std_h": 3.5,
            "provenance": "reported",
        },
        {
            "port_id": "DEHAM",
            "name": "Port of Hamburg",
            "unlocode": "DEHAM",
            "lat": 53.53,
            "lon": 9.97,
            "max_draft_m": 15.1,
            "ops_available": True,
            "ops_price_per_kwh": 0.26,
            "ops_clean_grid_factor": 290.0,
            "bunker_stock_tonnes": {
                "mgo": 18000.0,
                "lng_fossil": 8000.0,
                "lng_bio": 3000.0,
                "methanol_bio": 2500.0,
                "methanol_e": 1200.0,
            },
            "bunker_price_spread": {"mgo": 1.02},
            "congestion_delay_mean_h": 4.0,
            "congestion_delay_std_h": 1.8,
            "provenance": "reported",
        },
        {
            "port_id": "BEANR",
            "name": "Port of Antwerp-Bruges",
            "unlocode": "BEANR",
            "lat": 51.28,
            "lon": 4.34,
            "max_draft_m": 15.8,
            "ops_available": True,
            "ops_price_per_kwh": 0.23,
            "ops_clean_grid_factor": 160.0,
            "bunker_stock_tonnes": {
                "hfo": 30000.0,
                "mgo": 20000.0,
                "methanol_grey": 9000.0,
                "methanol_bio": 3500.0,
                "methanol_e": 1500.0,
                "ammonia_green": 800.0,
            },
            "bunker_price_spread": {"hfo": 1.01, "mgo": 1.01},
            "congestion_delay_mean_h": 3.5,
            "congestion_delay_std_h": 1.5,
            "provenance": "reported",
        },
        {
            "port_id": "AEJEA",
            "name": "Jebel Ali Port (Dubai)",
            "unlocode": "AEJEA",
            "lat": 25.01,
            "lon": 55.06,
            "max_draft_m": 17.0,
            "ops_available": False,
            "ops_price_per_kwh": 0.20,
            "ops_clean_grid_factor": 450.0,
            "bunker_stock_tonnes": {
                "hfo": 45000.0,
                "mgo": 22000.0,
                "lng_fossil": 10000.0,
            },
            "bunker_price_spread": {"hfo": 0.95, "mgo": 0.96},
            "congestion_delay_mean_h": 3.0,
            "congestion_delay_std_h": 1.2,
            "provenance": "reported",
        },
        {
            "port_id": "GRPIR",
            "name": "Port of Piraeus",
            "unlocode": "GRPIR",
            "lat": 37.94,
            "lon": 23.63,
            "max_draft_m": 18.5,
            "ops_available": False,
            "ops_price_per_kwh": 0.25,
            "ops_clean_grid_factor": 310.0,
            "bunker_stock_tonnes": {
                "hfo": 25000.0,
                "mgo": 15000.0,
                "lng_fossil": 5000.0,
            },
            "bunker_price_spread": {"hfo": 1.02, "mgo": 1.03},
            "congestion_delay_mean_h": 3.8,
            "congestion_delay_std_h": 1.6,
            "provenance": "reported",
        },
        {
            "port_id": "ZADUR",
            "name": "Port of Durban",
            "unlocode": "ZADUR",
            "lat": -29.87,
            "lon": 31.02,
            "max_draft_m": 12.8,
            "ops_available": False,
            "ops_price_per_kwh": 0.27,
            "ops_clean_grid_factor": 750.0,
            "bunker_stock_tonnes": {
                "hfo": 20000.0,
                "mgo": 10000.0,
            },
            "bunker_price_spread": {"hfo": 1.06, "mgo": 1.08},
            "congestion_delay_mean_h": 8.0,
            "congestion_delay_std_h": 4.0,
            "provenance": "reported",
        },
        {
            "port_id": "BRSSZ",
            "name": "Port of Santos",
            "unlocode": "BRSSZ",
            "lat": -23.96,
            "lon": -46.30,
            "max_draft_m": 14.5,
            "ops_available": False,
            "ops_price_per_kwh": 0.21,
            "ops_clean_grid_factor": 110.0,
            "bunker_stock_tonnes": {
                "hfo": 28000.0,
                "mgo": 12000.0,
                "methanol_bio": 2000.0,
            },
            "bunker_price_spread": {"hfo": 1.03, "mgo": 1.04},
            "congestion_delay_mean_h": 5.5,
            "congestion_delay_std_h": 2.2,
            "provenance": "reported",
        },
    ]


def get_routes() -> List[Dict[str, Any]]:
    return [
        {
            "route_id": "RTE_ASIA_EUR_01",
            "name": "Asia-Europe Mega Loop (Shanghai to Rotterdam)",
            "origin_port_id": "CNSHA",
            "destination_port_id": "NLRTM",
            "total_distance_nm": 10500.0,
            "demand_tonnes": 85000.0,
            "deadline_hours": 620.0,
            "legs": [
                {
                    "leg_id": "LEG_CNSHA_SGSIN",
                    "from_port_id": "CNSHA",
                    "to_port_id": "SGSIN",
                    "distance_nm": 2250.0,
                    "depth_m": 35.0,
                    "in_eca": False,
                    "baseline_eta_h": 125.0,
                    "weather_summary": {
                        "significant_wave_height_m": 1.6,
                        "wind_speed_knots": 12.0,
                        "relative_wind_angle_deg": 30.0,
                        "current_speed_knots": 0.4,
                    },
                    "provenance": "reported",
                },
                {
                    "leg_id": "LEG_SGSIN_AEJEA",
                    "from_port_id": "SGSIN",
                    "to_port_id": "AEJEA",
                    "distance_nm": 3300.0,
                    "depth_m": 60.0,
                    "in_eca": False,
                    "baseline_eta_h": 185.0,
                    "weather_summary": {
                        "significant_wave_height_m": 1.8,
                        "wind_speed_knots": 14.0,
                        "relative_wind_angle_deg": 40.0,
                        "current_speed_knots": 0.2,
                    },
                    "provenance": "reported",
                },
                {
                    "leg_id": "LEG_AEJEA_GRPIR",
                    "from_port_id": "AEJEA",
                    "to_port_id": "GRPIR",
                    "distance_nm": 3000.0,
                    "depth_m": 45.0,
                    "in_eca": False,
                    "baseline_eta_h": 168.0,
                    "weather_summary": {
                        "significant_wave_height_m": 1.4,
                        "wind_speed_knots": 10.0,
                        "relative_wind_angle_deg": 15.0,
                        "current_speed_knots": 0.1,
                    },
                    "provenance": "reported",
                },
                {
                    "leg_id": "LEG_GRPIR_NLRTM",
                    "from_port_id": "GRPIR",
                    "to_port_id": "NLRTM",
                    "distance_nm": 1950.0,
                    "depth_m": 30.0,
                    "in_eca": True,  # English Channel / North Sea ECA
                    "baseline_eta_h": 110.0,
                    "weather_summary": {
                        "significant_wave_height_m": 2.2,
                        "wind_speed_knots": 18.0,
                        "relative_wind_angle_deg": 50.0,
                        "current_speed_knots": 0.6,
                    },
                    "provenance": "reported",
                },
            ],
            "provenance": "reported",
        },
        {
            "route_id": "RTE_TRANSPAC_01",
            "name": "Transpacific Express (Shanghai to Los Angeles)",
            "origin_port_id": "CNSHA",
            "destination_port_id": "USLAX",
            "total_distance_nm": 5700.0,
            "demand_tonnes": 65000.0,
            "deadline_hours": 330.0,
            "legs": [
                {
                    "leg_id": "LEG_CNSHA_MIDPAC",
                    "from_port_id": "CNSHA",
                    "to_port_id": "WAYPOINT_MIDPAC",
                    "distance_nm": 2850.0,
                    "depth_m": 2000.0,
                    "in_eca": False,
                    "baseline_eta_h": 158.0,
                    "weather_summary": {
                        "significant_wave_height_m": 2.5,
                        "wind_speed_knots": 19.0,
                        "relative_wind_angle_deg": 60.0,
                        "current_speed_knots": 0.3,
                    },
                    "provenance": "reported",
                },
                {
                    "leg_id": "LEG_MIDPAC_USLAX",
                    "from_port_id": "WAYPOINT_MIDPAC",
                    "to_port_id": "USLAX",
                    "distance_nm": 2850.0,
                    "depth_m": 1500.0,
                    "in_eca": True,  # North American 200nm ECA zone
                    "baseline_eta_h": 158.0,
                    "weather_summary": {
                        "significant_wave_height_m": 2.0,
                        "wind_speed_knots": 16.0,
                        "relative_wind_angle_deg": 45.0,
                        "current_speed_knots": 0.2,
                    },
                    "provenance": "reported",
                },
            ],
            "provenance": "reported",
        },
        {
            "route_id": "RTE_INTRA_EUR_01",
            "name": "North Sea Green Feeder Corridor",
            "origin_port_id": "NLRTM",
            "destination_port_id": "DEHAM",
            "total_distance_nm": 520.0,
            "demand_tonnes": 18000.0,
            "deadline_hours": 42.0,
            "legs": [
                {
                    "leg_id": "LEG_NLRTM_BEANR",
                    "from_port_id": "NLRTM",
                    "to_port_id": "BEANR",
                    "distance_nm": 85.0,
                    "depth_m": 16.0,
                    "in_eca": True,  # 100% ECA
                    "baseline_eta_h": 6.5,
                    "weather_summary": {
                        "significant_wave_height_m": 1.2,
                        "wind_speed_knots": 12.0,
                        "relative_wind_angle_deg": 25.0,
                        "current_speed_knots": 0.8,
                    },
                    "provenance": "reported",
                },
                {
                    "leg_id": "LEG_BEANR_DEHAM",
                    "from_port_id": "BEANR",
                    "to_port_id": "DEHAM",
                    "distance_nm": 435.0,
                    "depth_m": 20.0,
                    "in_eca": True,  # 100% ECA
                    "baseline_eta_h": 32.0,
                    "weather_summary": {
                        "significant_wave_height_m": 1.7,
                        "wind_speed_knots": 15.0,
                        "relative_wind_angle_deg": 35.0,
                        "current_speed_knots": 0.7,
                    },
                    "provenance": "reported",
                },
            ],
            "provenance": "reported",
        },
    ]


def get_scenarios() -> List[Dict[str, Any]]:
    return [
        {
            "scenario_id": "SCN_NOMINAL",
            "name": "Nominal Baseline Conditions",
            "scenario_type": "nominal",
            "weather_multiplier": 1.0,
            "port_delay_hours": {},
            "fuel_price_multipliers": {},
            "carbon_tax_usd_tonne": 85.0,
            "bunker_outages": [],
            "seed": 42,
            "probability": 0.50,
            "provenance": "simulated",
        },
        {
            "scenario_id": "SCN_NORTH_STORM",
            "name": "Severe North Atlantic / North Sea Winter Gale",
            "scenario_type": "storm",
            "weather_multiplier": 1.45,
            "port_delay_hours": {"NLRTM": 8.0, "DEHAM": 6.0},
            "fuel_price_multipliers": {},
            "carbon_tax_usd_tonne": 85.0,
            "bunker_outages": [],
            "seed": 101,
            "probability": 0.15,
            "provenance": "simulated",
        },
        {
            "scenario_id": "SCN_PORT_CONGESTION",
            "name": "Global Chokepoint & Hub Congestion Crisis",
            "scenario_type": "congestion",
            "weather_multiplier": 1.05,
            "port_delay_hours": {"SGSIN": 14.0, "CNSHA": 18.0, "USLAX": 22.0},
            "fuel_price_multipliers": {},
            "carbon_tax_usd_tonne": 85.0,
            "bunker_outages": [],
            "seed": 202,
            "probability": 0.15,
            "provenance": "simulated",
        },
        {
            "scenario_id": "SCN_FUEL_PRICE_SHOCK",
            "name": "Bio-Feedstock Shortage & E-Fuel Cost Surge",
            "scenario_type": "fuel_shock",
            "weather_multiplier": 1.0,
            "port_delay_hours": {},
            "fuel_price_multipliers": {
                "methanol_bio": 1.45,
                "methanol_e": 1.35,
                "lng_bio": 1.40,
                "ammonia_green": 1.50,
            },
            "carbon_tax_usd_tonne": 85.0,
            "bunker_outages": [],
            "seed": 303,
            "probability": 0.10,
            "provenance": "simulated",
        },
        {
            "scenario_id": "SCN_CARBON_TAX_HIKE",
            "name": "Accelerated EU ETS / IMO Global GHG Pricing ($160/t)",
            "scenario_type": "carbon_shock",
            "weather_multiplier": 1.0,
            "port_delay_hours": {},
            "fuel_price_multipliers": {},
            "carbon_tax_usd_tonne": 160.0,
            "bunker_outages": [],
            "seed": 404,
            "probability": 0.05,
            "provenance": "simulated",
        },
        {
            "scenario_id": "SCN_BUNKER_OUTAGE",
            "name": "Alternative Fuel Stockout at Key Hubs",
            "scenario_type": "bunker_outage",
            "weather_multiplier": 1.0,
            "port_delay_hours": {},
            "fuel_price_multipliers": {},
            "carbon_tax_usd_tonne": 85.0,
            "bunker_outages": [["NLRTM", "methanol_e"], ["SGSIN", "ammonia_green"]],
            "seed": 505,
            "probability": 0.05,
            "provenance": "simulated",
        },
    ]


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    fuel_dir = os.path.join(root, "data", "fuel_catalog")
    sample_dir = os.path.join(root, "data", "sample")
    scenario_dir = os.path.join(root, "data", "scenarios")

    os.makedirs(fuel_dir, exist_ok=True)
    os.makedirs(sample_dir, exist_ok=True)
    os.makedirs(scenario_dir, exist_ok=True)

    with open(os.path.join(fuel_dir, "fuels.json"), "w", encoding="utf-8") as f:
        json.dump(get_fuels(), f, indent=2)
    print("Created data/fuel_catalog/fuels.json")

    with open(os.path.join(sample_dir, "vessels.json"), "w", encoding="utf-8") as f:
        json.dump(get_vessels(), f, indent=2)
    print("Created data/sample/vessels.json")

    with open(os.path.join(sample_dir, "ports.json"), "w", encoding="utf-8") as f:
        json.dump(get_ports(), f, indent=2)
    print("Created data/sample/ports.json")

    with open(os.path.join(sample_dir, "routes.json"), "w", encoding="utf-8") as f:
        json.dump(get_routes(), f, indent=2)
    print("Created data/sample/routes.json")

    with open(os.path.join(scenario_dir, "scenarios.json"), "w", encoding="utf-8") as f:
        json.dump(get_scenarios(), f, indent=2)
    print("Created data/scenarios/scenarios.json")


if __name__ == "__main__":
    main()
